INSERT INTO indicators (slug,name_ru,name_kk,category,description,unit,periodicity,source_url,source_format,aggregation_type,normalization_allowed,formula,territorial_levels) VALUES
('population','Численность населения','Халық саны','demography','На начало периода','человек','annual','https://stat.gov.kz/ru/industries/socialtatistics/demography/dynamic-tables/','csv','stock','["absolute","per_capita","per_km2","change_pct","deviation_national"]',NULL,'{0,1,2}'),
('population_density','Плотность населения','Халықтың тығыздығы','demography','Расчётный показатель','чел./км²','annual','https://stat.gov.kz/ru/industries/socialtatistics/demography/dynamic-tables/','derived','ratio','["absolute"]','{"expression":"population / area_km2"}','{1,2}'),
('population_change_pct','Изменение населения','Халық санының өзгеруі','demography','К предыдущему году','%','annual','https://stat.gov.kz/ru/industries/socialtatistics/demography/dynamic-tables/','derived','ratio','["absolute"]','{"expression":"(population-lag(population))/lag(population)*100"}','{0,1,2}'),
('births','Число родившихся','Туғандар саны','demography',NULL,'человек','annual','https://stat.gov.kz/ru/industries/socialtatistics/demography/dynamic-tables/','csv','sum','["absolute","per_1000","change_pct"]',NULL,'{0,1,2}'),
('birth_rate','Коэффициент рождаемости','Туу коэффициенті','demography',NULL,'на 1000','annual','https://stat.gov.kz/ru/industries/socialtatistics/demography/dynamic-tables/','csv','weighted_mean','["absolute","deviation_national"]',NULL,'{0,1,2}'),
('deaths','Число умерших','Қайтыс болғандар саны','demography',NULL,'человек','annual','https://stat.gov.kz/ru/industries/socialtatistics/demography/dynamic-tables/','csv','sum','["absolute","per_1000","change_pct"]',NULL,'{0,1,2}'),
('death_rate','Коэффициент смертности','Өлім коэффициенті','demography',NULL,'на 1000','annual','https://stat.gov.kz/ru/industries/socialtatistics/demography/dynamic-tables/','csv','weighted_mean','["absolute","deviation_national"]',NULL,'{0,1,2}'),
('natural_growth','Естественный прирост','Табиғи өсім','demography',NULL,'человек','annual','https://stat.gov.kz/ru/industries/socialtatistics/demography/dynamic-tables/','derived','sum','["absolute","per_1000"]','{"expression":"births - deaths"}','{0,1,2}'),
('arrivals','Прибывшие','Келгендер','demography',NULL,'человек','annual','https://stat.gov.kz/ru/industries/socialtatistics/demography/dynamic-tables/','csv','sum','["absolute","per_1000"]',NULL,'{0,1,2}'),
('departures','Выбывшие','Кеткендер','demography',NULL,'человек','annual','https://stat.gov.kz/ru/industries/socialtatistics/demography/dynamic-tables/','csv','sum','["absolute","per_1000"]',NULL,'{0,1,2}'),
('migration_balance','Сальдо миграции','Көші-қон сальдосы','demography',NULL,'человек','annual','https://stat.gov.kz/ru/industries/socialtatistics/demography/dynamic-tables/','derived','sum','["absolute","per_1000"]','{"expression":"arrivals - departures"}','{0,1,2}'),
('labor_force','Рабочая сила','Жұмыс күші','labor',NULL,'тыс. человек','quarterly','https://stat.gov.kz/ru/industries/labor-and-income/stat-empt-unempl/','xlsx','mean','["absolute","share_pct","change_pct"]',NULL,'{0,1}'),
('employment','Занятое население','Жұмыспен қамтылған халық','labor',NULL,'тыс. человек','quarterly','https://stat.gov.kz/ru/industries/labor-and-income/stat-empt-unempl/','xlsx','mean','["absolute","share_pct","change_pct"]',NULL,'{0,1}'),
('unemployment_rate','Уровень безработицы','Жұмыссыздық деңгейі','labor',NULL,'%','quarterly','https://stat.gov.kz/ru/industries/labor-and-income/stat-empt-unempl/','xlsx','weighted_mean','["absolute","deviation_national"]',NULL,'{0,1}'),
('income_per_capita','Среднедушевые номинальные доходы','Жан басына шаққандағы атаулы табыс','income',NULL,'₸','quarterly','https://stat.gov.kz/ru/industries/labor-and-income/stat-life/','xlsx','weighted_mean','["absolute","change_pct","deviation_national"]',NULL,'{0,1}'),
('grp','Валовой региональный продукт','Жалпы өңірлік өнім','economy',NULL,'млн ₸','annual','https://stat.gov.kz/ru/industries/eco-nomy/national-accounts/','xlsx','sum','["absolute","per_capita","change_pct"]',NULL,'{1}'),
('grp_per_capita','ВРП на душу населения','Жан басына шаққандағы ЖӨӨ','economy',NULL,'₸/чел.','annual','https://stat.gov.kz/ru/industries/eco-nomy/national-accounts/','derived','ratio','["absolute","deviation_national"]','{"expression":"grp / population"}','{1}'),
('industrial_output','Промышленное производство','Өнеркәсіп өндірісі','industry',NULL,'млн ₸','monthly','https://stat.gov.kz/ru/industries/business-statistics/stat-industrial-production/','xlsx','sum','["absolute","per_capita","change_pct"]',NULL,'{0,1}'),
('fixed_capital_investment','Инвестиции в основной капитал','Негізгі капиталға инвестициялар','investment',NULL,'млн ₸','monthly','https://stat.gov.kz/ru/industries/business-statistics/stat-invest/','xlsx','sum','["absolute","per_capita","change_pct"]',NULL,'{0,1,2}'),
('housing_commissioned','Ввод жилья','Тұрғын үйді пайдалануға беру','construction',NULL,'м²','monthly','https://stat.gov.kz/ru/industries/business-statistics/stat-inno-build/','xlsx','sum','["absolute","per_capita","change_pct"]',NULL,'{0,1,2}')
ON CONFLICT (slug) DO UPDATE SET source_url=EXCLUDED.source_url, normalization_allowed=EXCLUDED.normalization_allowed;

